INSERT INTO USER (USER_ID, NAME, EMAIL, PASSWORD) VALUES (1, 'John Doe', 'john.doe@testmail.com', 'j0hnd03s3cr3t');
INSERT INTO USER (USER_ID, NAME, EMAIL, PASSWORD) VALUES (2, 'Peter Smith', 'peter.smith@testmail.com', 'p3t3rsm1ths3cr3t');
INSERT INTO USER (USER_ID, NAME, EMAIL, PASSWORD) VALUES (3, 'Frank Perkins', 'frank.perkins@testmail.com', 'fr4nkp3rk1nss3cr3t');

INSERT INTO PHONE (PHONE_ID, USER_ID, COUNTRYCODE, CITYCODE, NUMBER) VALUES (1, 1, 56, 1, 12345678);
INSERT INTO PHONE (PHONE_ID, USER_ID, COUNTRYCODE, CITYCODE, NUMBER) VALUES (2, 2, 56, 1, 22345678);
INSERT INTO PHONE (PHONE_ID, USER_ID, COUNTRYCODE, CITYCODE, NUMBER) VALUES (3, 2, 56, 1, 27654321);
INSERT INTO PHONE (PHONE_ID, USER_ID, COUNTRYCODE, CITYCODE, NUMBER) VALUES (4, 3, 56, 1, 32345678);
INSERT INTO PHONE (PHONE_ID, USER_ID, COUNTRYCODE, CITYCODE, NUMBER) VALUES (5, 3, 56, 1, 37654321);
INSERT INTO PHONE (PHONE_ID, USER_ID, COUNTRYCODE, CITYCODE, NUMBER) VALUES (6, 3, 56, 1, 32344321);
